### PR TITLE
Community page bug

### LINKED ISSUE #1210: Bug: community cover images not showing
Community pages turned into functional recently maybe bug introduced during that transition or it was existed way before. Regardless, community cover images are not loading, this needs checking.

### PR DESCRIPTION
**Pull request by MTSaeed**
**What does this PR?**

Update the profile and cover image not override the cover image. Update just effect on corresponding discipline.
 
**Steps to reproduce**

1. Upload any image as profile or cover image.
2. Do empty cache and hard reload for instantaneous change. Both profile and cover images behaves separately and not override each other.

Fixes #1210, improves

### CODE REVIEW

File: src/common/components/community-cover/index.tsx [hunk 1]
```diff
@@ -163,9 +163,13 @@ export class CommunityCover extends Component<Props> {
 
     let bgImage = global.theme === "day" ? coverFallbackDay : coverFallbackNight;
     if (community) {
-      bgImage = `https://images.ecency.com/${global.canUseWebp ? "webp/" : ""}u/${
-        community.name
-      }/cover`;
+      if (Object.keys(account).includes("profile") && account["profile"].cover_image) {
```
Comment (feruzm) [inline src/common/components/community-cover/index.tsx:166]: @MTSaeed This is unnecesary, because our image server already does the checking for profile.cover_image. Please keep `.../cover`.

**Review by feruzm — APPROVED** [review]
lgtm
